export const content = {
  he: {
    dir: "rtl", title: "אלקטרוליטים", badge: "אתר לימודי אינטראקטיבי ⚡",
    subtitle: "אלקטרוליט הוא חומר שיוצר יונים כאשר הוא מומס במים או מותך, ולכן מאפשר הולכה חשמלית. בגוף האדם יונים כמו נתרן, אשלגן וכלוריד חיוניים לעצבים, לשרירים, ללב ולמאזן הנוזלים.",
    languageButton: "English", darkButton: "מצב בהיר", lightButton: "מצב כהה", share: "שתף", copied: "הועתק!", soundOn: "צליל פעיל", soundOff: "צליל כבוי",
    wordTitle: "מה פירוש המילה אלקטרוליט?", wordIntro: "המונח Electrolyte נוצר מן הרעיון של חשמל ושל פירוק או התרה ליונים:", electro: "Electro — קשור לחשמל.", lyte: "הסיומת ‎-lyte קשורה לשורש יווני של שחרור, פירוק או התרה; היא אינה מילה אנגלית עצמאית רגילה.", wordSummary: "כאשר אלקטרוליט מתמוסס ונוצרים יונים ניידים, התמיסה יכולה להוליך זרם חשמלי.",
    tabs: { role: "תפקיד", balance: "חוסר / עודף", visual: "איך נראה?", etymology: "אטימולוגיה", history: "היסטוריה מדעית" },
    labels: { role: "תפקיד בגוף", importance: "למה זה חשוב?", low: "כאשר יש חוסר", high: "כאשר יש עודף", visual: "מראה ברמה האטומית", etymology: "ניתוח אטימולוגי", elementHistory: "גילוי היסוד או התרכובת", biologyHistory: "הבנת התפקיד הביולוגי" },
    factsTitle: "דברים חשובים שכדאי לזכור",
    facts: [["איזון הוא העיקר", "לא תמיד יותר הוא טוב. הגוף זקוק לטווח מאוזן של אלקטרוליטים."], ["הכליות מנהלות את המערכת", "הכליות מסננות, שומרות או מפרישות אלקטרוליטים בהתאם לצורכי הגוף."], ["אובדן נוזלים משפיע", "הזעה, שלשולים, הקאות או שתייה לא מאוזנת עלולים לשנות את רמות האלקטרוליטים."]],
    disclaimerTitle: "הבהרה רפואית חשובה", disclaimer: "המידע באתר נועד ללימוד ולהעשרה בלבד. הוא אינו מהווה ייעוץ רפואי, אבחון או המלצה לטיפול. תסמינים של הפרעת אלקטרוליטים עלולים להיות בלתי־ספציפיים ולעיתים דורשים בדיקות דם והערכה רפואית.", urgent: "במצב של בלבול חריף, עילפון, פרכוס, חולשה קשה, כאב בחזה או חשד להפרעה בקצב הלב — יש לפנות לקבלת טיפול רפואי דחוף.",
    sourcesTitle: "מקורות מומלצים", sourcesIntro: "המידע נוסח לצורכי לימוד על בסיס מקורות רפואיים וכימיים כלליים. טווחי מעבדה והנחיות טיפול עשויים להשתנות בין מוסדות ומטופלים.",
    ions: [
      { id: "sodium", name: "נתרן", symbol: "Na⁺", emoji: "💧", color: "from-sky-400 to-blue-600", location: "בעיקר מחוץ לתאים ובנוזל הדם", role: "מסייע לשמירת נפח הנוזלים, להעברת אותות עצביים ולפעילות השרירים.", importance: "שינויים מהירים בריכוז הנתרן משפיעים על תנועת מים אל תוך תאים ומחוצה להם, ובמיוחד על תאי המוח.", low: "היפונתרמיה עלולה להתבטא בבחילה, כאב ראש, חולשה או בלבול; במקרים חמורים עלולים להופיע פרכוסים.", high: "היפרנתרמיה קשורה לרוב למחסור יחסי במים ועלולה לגרום לצמא, חולשה, בלבול ותסמינים נוירולוגיים.", etymology: ["Sodium קשור היסטורית למילה soda.", "הסמל Na בא מן השם Natrium.", "Natrium קשור ל-Natron, מלח מינרלי עתיק.", "השם העברי נתרן קשור למילה נתר."], elementHistory: "המפרי דייבי בודד נתרן מתכתי בשנת 1807 באמצעות אלקטרוליזה של נתרן הידרוקסידי מותך.", biologyHistory: "ההבנה המודרנית של מפל הנתרן, פוטנציאל הממברנה ומשאבת נתרן־אשלגן התפתחה בהדרגה במאות ה־19 וה־20.", visual: "Na⁺ הוא אטום נתרן שאיבד אלקטרון אחד ולכן נושא מטען חיובי." },
      { id: "potassium", name: "אשלגן", symbol: "K⁺", emoji: "❤️", color: "from-emerald-400 to-green-600", location: "בעיקר בתוך התאים", role: "חיוני לפעילות החשמלית של תאים, לקצב הלב ולתפקוד העצבים והשרירים.", importance: "שינויים ברמת האשלגן עלולים לשנות את המתח החשמלי של ממברנות התאים ואת הולכת האות בלב.", low: "היפוקלמיה עלולה לגרום לחולשה, התכווצויות ולעיתים הפרעות בקצב הלב.", high: "היפרקלמיה עלולה לפגוע בהולכה החשמלית בלב ולעיתים אינה גורמת תסמינים מוקדמים ברורים.", etymology: ["Potassium נגזר מן Potash.", "הסמל K בא מן Kalium.", "Kalium קשור למונח alkali.", "השם העברי אשלגן קשור לאשלג."], elementHistory: "המפרי דייבי בודד אשלגן מתכתי בשנת 1807 באמצעות אלקטרוליזה של אשלגן הידרוקסידי מותך.", biologyHistory: "ההבחנה בין ריכוז אשלגן גבוה בתוך התא לריכוז נמוך מחוצה לו הייתה יסוד להבנת חשמל התא ופיזיולוגיית הלב.", visual: "K⁺ הוא אטום אשלגן שאיבד אלקטרון אחד." },
      { id: "calcium", name: "סידן", symbol: "Ca²⁺", emoji: "🦴", color: "from-violet-400 to-purple-700", location: "בעצמות, בשיניים, בדם ובתאים", role: "חשוב למבנה העצמות והשיניים, לכיווץ שרירים, לקרישת דם ולאיתות בין תאים.", importance: "רוב הסידן בגוף נמצא בשלד, אך הכמות הקטנה בנוזל החוץ־תאי ובתאים חיונית לתפקוד מיידי.", low: "היפוקלצמיה עלולה לגרום לנימול, עוויתות, התכווצויות ולעיתים הפרעות בקצב הלב.", high: "היפרקלצמיה עלולה לגרום לצמא, עצירות, עייפות, בלבול או אבנים בכליות.", etymology: ["Calcium בא מן הלטינית calx — סיד או אבן גיר.", "Ca הוא קיצור של Calcium.", "תרכובות סידן היו מוכרות זמן רב בסיד ובאבן גיר.", "השם העברי סידן קשור לסיד."], elementHistory: "דייבי הכין סגסוגת המכילה סידן בשנת 1808; בידוד סידן טהור יותר הושג מאוחר יותר.", biologyHistory: "במהלך המאות ה־19 וה־20 התבררו תפקידי הסידן בכיווץ שריר, בקרישה ובאיתות תאי.", visual: "Ca²⁺ הוא אטום סידן שאיבד שני אלקטרונים." },
      { id: "magnesium", name: "מגנזיום", symbol: "Mg²⁺", emoji: "💪", color: "from-amber-400 to-orange-600", location: "בתאים, בשרירים ובעצמות", role: "משתתף במאות תגובות אנזימטיות, ביצירת אנרגיה ובתפקוד עצבים ושרירים.", importance: "מגנזיום מסייע לייצוב ATP, חומצות גרעין וממברנות ומשפיע גם על מאזן אשלגן וסידן.", low: "חוסר עלול לגרום לחולשה, רעד, התכווצויות ולעיתים הפרעות בקצב הלב.", high: "עודף משמעותי נדיר יותר באנשים עם תפקוד כליות תקין, אך עלול לגרום לישנוניות, חולשה ולחץ דם נמוך.", etymology: ["Magnesium קשור לשם Magnesia.", "Mg הוא קיצור של Magnesium.", "השם נקשר למינרלים שנמצאו באזור מגנסיה.", "המונח נשמר בשפות רבות."], elementHistory: "דייבי הכין צורה לא טהורה של מגנזיום בשנת 1808; אנטואן ביסי השיג מתכת טהורה יותר בשנת 1831.", biologyHistory: "תפקידי המגנזיום באנזימים, ב-ATP ובפיזיולוגיה עצבית־שרירית הובהרו בהדרגה עם התפתחות הביוכימיה.", visual: "Mg²⁺ הוא אטום מגנזיום שאיבד שני אלקטרונים." },
      { id: "chloride", name: "כלוריד", symbol: "Cl⁻", emoji: "🧪", color: "from-cyan-400 to-teal-600", location: "בעיקר מחוץ לתאים ובדם", role: "מסייע למאזן נוזלים, למאזן חומצה־בסיס וליצירת חומצת הקיבה.", importance: "כלוריד הוא האניון העיקרי בנוזל החוץ־תאי ופועל בתיאום עם נתרן וביקרבונט.", low: "היפוכלורמיה עשויה להופיע לאחר הקאות ממושכות, שימוש בתרופות מסוימות או הפרעות חומצה־בסיס.", high: "היפרכלורמיה עשויה להופיע בהתייבשות, בהפרעות כליה או בחמצת מטבולית מסוימת.", etymology: ["Chloride הוא היון השלילי של היסוד chlorine.", "Chlorine בא מן היוונית chlōros — ירקרק־צהבהב.", "Cl הוא הסמל של כלור.", "כלוריד נוצר כאשר אטום כלור מקבל אלקטרון."], elementHistory: "קרל וילהלם שלה הפיק כלור בשנת 1774, אך המפרי דייבי קבע בשנת 1810 שמדובר ביסוד. מלחי כלוריד היו מוכרים זמן רב קודם לכן.", biologyHistory: "תפקיד הכלוריד בנוזלי הגוף, בחומצת הקיבה ובהחלפת כלוריד־ביקרבונט התברר עם התפתחות הפיזיולוגיה והכימיה הקלינית.", visual: "Cl⁻ הוא אטום כלור שקיבל אלקטרון ולכן נושא מטען שלילי." },
      { id: "phosphate", name: "פוספט", symbol: "PO₄³⁻", emoji: "⚡", color: "from-rose-400 to-pink-700", location: "בתאים, בעצמות, בשיניים ובדם", role: "חשוב ל-ATP, ל-DNA ול-RNA, לממברנות, למאזן חומצה־בסיס ולבריאות העצם.", importance: "פוספט הוא משפחה של יונים ותרכובות של חומצה זרחתית; בגוף צורתו תלויה בחומציות הסביבה.", low: "היפופוספטמיה עלולה לגרום לחולשה, כאבי שרירים ובמקרים חמורים לפגיעה בנשימה או בתפקוד העצבי.", high: "היפרפוספטמיה קשורה לעיתים קרובות לירידה בתפקוד הכליות ומשפיעה על מאזן סידן־זרחן.", etymology: ["Phosphate הוא יון או מלח של חומצה זרחתית.", "Phosphorus בא מן היוונית ומשמעותו נושא אור.", "השם קשור לזוהר של זרחן לבן.", "פוספט אינו היסוד זרחן עצמו אלא תרכובת המכילה זרחן וחמצן."], elementHistory: "הניג ברנד גילה את היסוד זרחן בשנת 1669. הוא לא גילה את יון הפוספט, שהיה קיים ומוכר בתרכובות טבעיות עוד קודם לכן.", biologyHistory: "חשיבות הפוספט בעצמות, בחומצות גרעין וב-ATP התבררה בשלבים עם התפתחות הכימיה האורגנית והביוכימיה.", visual: "PO₄³⁻ הוא יון רב־אטומי המורכב מזרחן וארבעה אטומי חמצן; במים קיימות גם צורות ממוּטנות אחרות." }
    ],
    sources: [{ title: "MedlinePlus — Fluid and Electrolyte Balance", url: "https://medlineplus.gov/fluidandelectrolytebalance.html" }, { title: "Merck Manual — Overview of Electrolytes", url: "https://www.merckmanuals.com/home/hormonal-and-metabolic-disorders/electrolyte-balance/overview-of-electrolytes" }, { title: "NIH Office of Dietary Supplements", url: "https://ods.od.nih.gov/" }, { title: "Royal Society of Chemistry — Periodic Table", url: "https://www.rsc.org/periodic-table" }]
  },
  en: {
    dir: "ltr", title: "Electrolytes", badge: "Interactive learning site ⚡",
    subtitle: "An electrolyte is a substance that forms ions when dissolved in water or melted, allowing electrical conduction. In the human body, ions such as sodium, potassium, and chloride are essential for nerves, muscles, the heart, and fluid balance.",
    languageButton: "עברית", darkButton: "Light mode", lightButton: "Dark mode", share: "Share", copied: "Copied!", soundOn: "Sound on", soundOff: "Sound off",
    wordTitle: "What does the word electrolyte mean?", wordIntro: "The term Electrolyte combines electricity with release or separation into ions:", electro: "Electro — related to electricity.", lyte: "The suffix -lyte is related to a Greek root for loosening, releasing, or dissolving; it is not an ordinary standalone English word.", wordSummary: "When an electrolyte dissolves and mobile ions form, the solution can conduct electric current.",
    tabs: { role: "Role", balance: "Low / high", visual: "Atomic view", etymology: "Etymology", history: "Scientific history" },
    labels: { role: "Role in the body", importance: "Why it matters", low: "When levels are low", high: "When levels are high", visual: "Atomic-level view", etymology: "Etymological analysis", elementHistory: "Element or compound history", biologyHistory: "Understanding the biological role" },
    factsTitle: "Important points to remember", facts: [["Balance matters", "More is not always better; the body needs electrolytes within balanced ranges."], ["The kidneys regulate the system", "The kidneys filter, retain, or excrete electrolytes according to the body's needs."], ["Fluid loss matters", "Sweating, diarrhea, vomiting, or unbalanced fluid intake can alter electrolyte levels."]],
    disclaimerTitle: "Important medical notice", disclaimer: "This site is for education and general information only. It is not medical advice, a diagnosis, or a treatment recommendation. Symptoms of electrolyte disorders can be nonspecific and may require blood tests and professional evaluation.", urgent: "Seek urgent medical care for severe confusion, fainting, seizures, profound weakness, chest pain, or suspected abnormal heart rhythm.",
    sourcesTitle: "Recommended sources", sourcesIntro: "The material is written for educational purposes using general medical and chemistry references. Laboratory ranges and treatment guidance can vary by institution and patient.",
    ions: [
      { id: "sodium", name: "Sodium", symbol: "Na⁺", emoji: "💧", color: "from-sky-400 to-blue-600", location: "Mainly outside cells and in blood plasma", role: "Helps regulate fluid volume, nerve impulses, and muscle activity.", importance: "Rapid changes in sodium concentration alter water movement across cell membranes, especially in the brain.", low: "Hyponatremia may cause nausea, headache, weakness, or confusion; severe cases can cause seizures.", high: "Hypernatremia usually reflects a relative water deficit and may cause thirst, weakness, confusion, and neurological symptoms.", etymology: ["Sodium is historically related to soda.", "The symbol Na comes from Natrium.", "Natrium is related to natron, an ancient mineral salt.", "The Hebrew name is also linked to natron."], elementHistory: "Humphry Davy isolated metallic sodium in 1807 by electrolyzing molten sodium hydroxide.", biologyHistory: "Modern understanding of sodium gradients, membrane potentials, and the sodium–potassium pump developed gradually in the nineteenth and twentieth centuries.", visual: "Na⁺ is a sodium atom that has lost one electron and therefore carries a positive charge." },
      { id: "potassium", name: "Potassium", symbol: "K⁺", emoji: "❤️", color: "from-emerald-400 to-green-600", location: "Mainly inside cells", role: "Essential for cellular electrical activity, heart rhythm, nerves, and muscles.", importance: "Changes in potassium can alter membrane voltage and electrical conduction in the heart.", low: "Hypokalemia may cause weakness, cramps, and sometimes abnormal heart rhythms.", high: "Hyperkalemia can impair cardiac conduction and may have few early symptoms.", etymology: ["Potassium derives from potash.", "The symbol K comes from Kalium.", "Kalium is related to alkali.", "The Hebrew name is linked to potash."], elementHistory: "Humphry Davy isolated metallic potassium in 1807 by electrolyzing molten potassium hydroxide.", biologyHistory: "The high intracellular and low extracellular potassium concentrations became central to understanding cellular electricity and cardiac physiology.", visual: "K⁺ is a potassium atom that has lost one electron." },
      { id: "calcium", name: "Calcium", symbol: "Ca²⁺", emoji: "🦴", color: "from-violet-400 to-purple-700", location: "In bones, teeth, blood, and cells", role: "Important for bones and teeth, muscle contraction, blood clotting, and cell signaling.", importance: "Most calcium is stored in the skeleton, while the small fraction in body fluids and cells is vital for immediate function.", low: "Hypocalcemia may cause tingling, spasms, cramps, and sometimes abnormal heart rhythms.", high: "Hypercalcemia may cause thirst, constipation, fatigue, confusion, or kidney stones.", etymology: ["Calcium comes from Latin calx, meaning lime or limestone.", "Ca is the chemical symbol for calcium.", "Calcium compounds were long known in lime and limestone.", "The Hebrew name is related to lime."], elementHistory: "Davy prepared a calcium-containing amalgam in 1808; purer calcium was isolated later.", biologyHistory: "Calcium's roles in muscle contraction, clotting, and cellular signaling were clarified during the nineteenth and twentieth centuries.", visual: "Ca²⁺ is a calcium atom that has lost two electrons." },
      { id: "magnesium", name: "Magnesium", symbol: "Mg²⁺", emoji: "💪", color: "from-amber-400 to-orange-600", location: "In cells, muscles, and bones", role: "Participates in hundreds of enzyme reactions, energy production, and nerve and muscle function.", importance: "Magnesium helps stabilize ATP, nucleic acids, and membranes and also affects potassium and calcium balance.", low: "Deficiency may cause weakness, tremor, cramps, and sometimes abnormal heart rhythms.", high: "Marked excess is uncommon with normal kidney function but can cause drowsiness, weakness, and low blood pressure.", etymology: ["Magnesium is related to the name Magnesia.", "Mg is the chemical symbol.", "The name was associated with minerals found in the Magnesia region.", "The term was retained across many languages."], elementHistory: "Davy produced an impure form in 1808; Antoine Bussy obtained purer magnesium in 1831.", biologyHistory: "Its roles in enzymes, ATP, and neuromuscular physiology were clarified as biochemistry developed.", visual: "Mg²⁺ is a magnesium atom that has lost two electrons." },
      { id: "chloride", name: "Chloride", symbol: "Cl⁻", emoji: "🧪", color: "from-cyan-400 to-teal-600", location: "Mainly outside cells and in blood", role: "Supports fluid balance, acid–base balance, and stomach acid formation.", importance: "Chloride is the major extracellular anion and works with sodium and bicarbonate.", low: "Hypochloremia may follow prolonged vomiting, certain medicines, or acid–base disorders.", high: "Hyperchloremia may occur with dehydration, kidney disorders, or some forms of metabolic acidosis.", etymology: ["Chloride is the negative ion of chlorine.", "Chlorine comes from Greek chlōros, meaning greenish-yellow.", "Cl is the symbol for chlorine.", "Chloride forms when chlorine gains an electron."], elementHistory: "Carl Wilhelm Scheele produced chlorine in 1774, and Humphry Davy identified it as an element in 1810. Chloride salts had been known much earlier.", biologyHistory: "Chloride's roles in body fluids, stomach acid, and chloride–bicarbonate exchange emerged with modern physiology and clinical chemistry.", visual: "Cl⁻ is a chlorine atom that has gained one electron and therefore carries a negative charge." },
      { id: "phosphate", name: "Phosphate", symbol: "PO₄³⁻", emoji: "⚡", color: "from-rose-400 to-pink-700", location: "In cells, bones, teeth, and blood", role: "Important for ATP, DNA, RNA, membranes, acid–base balance, and bone health.", importance: "Phosphate is a family of ions and salts derived from phosphoric acid; its exact form depends on pH.", low: "Hypophosphatemia may cause weakness and muscle pain; severe cases can impair breathing or neurological function.", high: "Hyperphosphatemia is often associated with reduced kidney function and affects calcium–phosphate balance.", etymology: ["Phosphate is an ion or salt of phosphoric acid.", "Phosphorus comes from Greek and means light-bearer.", "The name refers to the glow of white phosphorus.", "Phosphate is not elemental phosphorus; it is an oxygen-containing compound."], elementHistory: "Hennig Brand discovered elemental phosphorus in 1669. He did not discover the phosphate ion, which already existed in familiar natural compounds.", biologyHistory: "Phosphate's roles in bone, nucleic acids, and ATP were established gradually with the development of organic chemistry and biochemistry.", visual: "PO₄³⁻ is a polyatomic ion containing phosphorus and four oxygen atoms; protonated forms also occur in water." }
    ],
    sources: [{ title: "MedlinePlus — Fluid and Electrolyte Balance", url: "https://medlineplus.gov/fluidandelectrolytebalance.html" }, { title: "Merck Manual — Overview of Electrolytes", url: "https://www.merckmanuals.com/home/hormonal-and-metabolic-disorders/electrolyte-balance/overview-of-electrolytes" }, { title: "NIH Office of Dietary Supplements", url: "https://ods.od.nih.gov/" }, { title: "Royal Society of Chemistry — Periodic Table", url: "https://www.rsc.org/periodic-table" }]
  }
};
