export const content = {
  he: {
    dir: "rtl",
    title: "אלקטרוליטים",
    badge: "אתר לימודי אינטראקטיבי ⚡",
    subtitle: "אלקטרוליטים הם מינרלים בעלי מטען חשמלי. כאשר הם מומסים בנוזלי הגוף, הם מתפרקים ליונים ומאפשרים פעילות חשמלית חיונית בעצבים, בשרירים, בלב ובמערכת מאזן הנוזלים.",
    languageButton: "English",
    darkButton: "מצב בהיר",
    lightButton: "מצב כהה",
    share: "שתף",
    copied: "הועתק!",
    wordTitle: "מה פירוש המילה אלקטרוליט?",
    wordIntro: "המילה Electrolyte מורכבת מרעיון של חשמל ופירוק:",
    electro: "Electro — קשור לחשמל.",
    lyte: "Lyte / Lysis — קשור לפירוק, המסה או התפרקות לחלקים.",
    wordSummary: "לכן אלקטרוליט הוא חומר שמתמוסס ומתפרק ליונים, והיונים האלה מסוגלים להוליך זרם חשמלי.",
    tabs: { role: "תפקיד", balance: "חוסר / עודף", visual: "איך נראה?", etymology: "אטימולוגיה", discovery: "גילוי" },
    labels: { role: "תפקיד בגוף", importance: "למה זה חשוב?", low: "כאשר יש חוסר", high: "כאשר יש עודף", visual: "מראה ברמה האטומית", etymology: "ניתוח אטימולוגי", discoverer: "שם המגלה", life: "שנות החיים", year: "שנת הגילוי", place: "מקום הגילוי", discovery: "נסיבות הגילוי" },
    factsTitle: "דברים חשובים שכדאי לזכור",
    facts: [["איזון הוא העיקר", "לא תמיד יותר הוא טוב. הגוף צריך טווח מאוזן של אלקטרוליטים."], ["הכליות מנהלות את המערכת", "הכליות מסננות, שומרות או מפרישות אלקטרוליטים לפי צורכי הגוף."], ["ספורט והתייבשות משפיעים", "הזעה, שלשולים, הקאות או שתייה לא מאוזנת יכולים לשנות את הרמות."]],
    ions: [
      { id: "sodium", name: "נתרן", symbol: "Na⁺", emoji: "💧", color: "from-sky-400 to-blue-600", location: "בעיקר מחוץ לתאים ובנוזל הדם", role: "נתרן עוזר לשמור על מאזן מים, העברת אותות עצביים, פעילות שרירים ולחץ דם.", importance: "איזון נתרן תקין חשוב לנפח הדם, ללחץ הדם ולתקשורת בין עצבים ושרירים.", low: "חוסר בנתרן נקרא היפונתרמיה ועלול לגרום לכאבי ראש, חולשה, בחילות, בלבול ועייפות.", high: "עודף נתרן נקרא היפרנתרמיה ועלול לגרום לצמא חזק, יובש, בלבול וחולשה.", etymology: ["Sodium קשור היסטורית למילה soda.", "Na מגיע מן Natrium.", "Natrium קשור ל-Natron, מלח מינרלי עתיק.", "בעברית השם נתרן קשור למונח הקדום נתר."], discoverer: "סר המפרי דייבי", life: "1778–1829", year: "1807", place: "המוסד המלכותי, לונדון", discovery: "דייבי בודד נתרן באלקטרוליזה של נתרן הידרוקסידי מותך.", visual: "Na⁺ הוא אטום נתרן שאיבד אלקטרון אחד ולכן נושא מטען חיובי." },
      { id: "potassium", name: "אשלגן", symbol: "K⁺", emoji: "❤️", color: "from-emerald-400 to-green-600", location: "בעיקר בתוך התאים", role: "אשלגן חיוני לפעילות חשמלית של תאים, קצב הלב, עצבים ושרירים.", importance: "שינוי קטן ברמת האשלגן עלול להשפיע על שרירים ועל קצב הלב.", low: "חוסר באשלגן נקרא היפוקלמיה ועלול לגרום לחולשה, התכווצויות ועייפות.", high: "עודף אשלגן נקרא היפרקלמיה ועלול להשפיע על קצב הלב.", etymology: ["Potassium בא מן Potash.", "K מגיע מן Kalium.", "Kalium קשור ל-alkali.", "בעברית אשלגן קשור לאשלג."], discoverer: "סר המפרי דייבי", life: "1778–1829", year: "1807", place: "המוסד המלכותי, לונדון", discovery: "דייבי בודד אשלגן באלקטרוליזה של אשלגן הידרוקסידי מותך.", visual: "K⁺ הוא אטום אשלגן שאיבד אלקטרון אחד." },
      { id: "calcium", name: "סידן", symbol: "Ca²⁺", emoji: "🦴", color: "from-violet-400 to-purple-700", location: "בעצמות, בשיניים, בדם ובתאים", role: "סידן חשוב לעצמות, שיניים, כיווץ שרירים, קרישת דם ותקשורת בין תאים.", importance: "סידן הוא גם חומר מבני וגם אות ביולוגי חשוב.", low: "חוסר בסידן עלול לגרום לנימול, עוויתות וחולשה.", high: "עודף סידן עלול לגרום לצמא, עצירות, עייפות ולעיתים בלבול.", etymology: ["Calcium בא מן הלטינית calx, סיד או אבן גיר.", "Ca הוא קיצור של Calcium.", "תרכובות סידן היו מוכרות באבן גיר ובסיד.", "בעברית סידן קשור לסיד."], discoverer: "סר המפרי דייבי", life: "1778–1829", year: "1808", place: "המוסד המלכותי, לונדון", discovery: "דייבי בודד סידן בעזרת אלקטרוליזה של תרכובות סידן.", visual: "Ca²⁺ הוא אטום סידן שאיבד שני אלקטרונים." },
      { id: "magnesium", name: "מגנזיום", symbol: "Mg²⁺", emoji: "💪", color: "from-amber-400 to-orange-600", location: "בתאים, בשרירים ובעצמות", role: "מגנזיום משתתף במאות תגובות אנזימטיות, אנרגיה, שרירים ועצבים.", importance: "מגנזיום מסייע לאנזימים רבים ותומך באנרגיה תאית.", low: "חוסר במגנזיום עלול לגרום להתכווצויות, רעד ועייפות.", high: "עודף מגנזיום נדיר יחסית ועלול לגרום לחולשה וישנוניות.", etymology: ["Magnesium קשור ל-Magnesia.", "Mg הוא קיצור של Magnesium.", "Magnesia נקשרה למינרלים דומים.", "השם משמר קשר לאזור מגנסיה."], discoverer: "סר המפרי דייבי", life: "1778–1829", year: "1808", place: "המוסד המלכותי, לונדון", discovery: "דייבי בודד כמות קטנה של מגנזיום באלקטרוליזה.", visual: "Mg²⁺ הוא אטום מגנזיום שאיבד שני אלקטרונים." },
      { id: "chloride", name: "כלוריד", symbol: "Cl⁻", emoji: "🧪", color: "from-cyan-400 to-teal-600", location: "בעיקר מחוץ לתאים ובדם", role: "כלוריד מסייע למאזן נוזלים, חומצה־בסיס, לחץ אוסמוטי וחומצת הקיבה.", importance: "כלוריד עובד עם נתרן לשמירת מאזן נוזלים וחומציות.", low: "חוסר בכלוריד עלול להופיע אחרי הקאות או אובדן נוזלים.", high: "עודף כלוריד עלול להופיע בהתייבשות או בהפרעות חומצה־בסיס.", etymology: ["Chloride הוא יון שלילי של Chlorine.", "Chlorine בא מן היוונית chlōros.", "Cl הוא קיצור של Chlorine.", "כלוריד הוא כלור שקיבל אלקטרון."], discoverer: "קרל וילהלם שלה", life: "1742–1786", year: "1774", place: "שוודיה", discovery: "שלה הפיק גז ירקרק־צהבהב מתגובה כימית; דייבי זיהה בהמשך שהוא יסוד.", visual: "Cl⁻ הוא אטום כלור שקיבל אלקטרון ולכן נושא מטען שלילי." },
      { id: "phosphate", name: "פוספט", symbol: "PO₄³⁻", emoji: "⚡", color: "from-rose-400 to-pink-700", location: "בתאים, בעצמות, בשיניים ובדם", role: "פוספט חשוב לאנרגיה תאית, DNA, RNA, ממברנות ובריאות העצם.", importance: "פוספט הוא חלק מרכזי מ-ATP, מטבע האנרגיה של התא.", low: "חוסר בפוספט עלול לגרום לחולשה, כאבי שרירים וירידה באנרגיה.", high: "עודף פוספט קשור לעיתים לתפקוד כליות ולמאזן סידן־זרחן.", etymology: ["Phosphate הוא יון של חומצה זרחתית.", "Phosphorus בא מן היוונית: נושא אור.", "השם קשור לזרחן לבן הזוהר בחושך.", "פוספט הוא צורת תרכובת של זרחן."], discoverer: "הניג ברנד", life: "בערך 1630–בערך 1710", year: "1669", place: "המבורג, גרמניה", discovery: "ברנד חיפש את אבן החכמים והפיק חומר זוהר משתן.", visual: "PO₄³⁻ הוא יון מורכב עם זרחן וארבעה אטומי חמצן." }
    ]
  },
  en: {
    dir: "ltr", title: "Electrolytes", badge: "Interactive learning site ⚡", subtitle: "Electrolytes are electrically charged minerals. When dissolved in body fluids, they split into ions and support essential electrical activity in nerves, muscles, the heart, and fluid balance.", languageButton: "עברית", darkButton: "Light mode", lightButton: "Dark mode", share: "Share", copied: "Copied!", wordTitle: "What does the word Electrolyte mean?", wordIntro: "The word Electrolyte combines electricity and breakdown:", electro: "Electro — related to electricity.", lyte: "Lyte / Lysis — related to splitting, dissolving, or breaking apart.", wordSummary: "An electrolyte is a substance that dissolves into ions, and those ions can conduct electrical current.", tabs: { role: "Role", balance: "Low / High", visual: "Appearance", etymology: "Etymology", discovery: "Discovery" }, labels: { role: "Role in the body", importance: "Why it matters", low: "When levels are low", high: "When levels are high", visual: "Atomic-level appearance", etymology: "Etymological breakdown", discoverer: "Discoverer", life: "Life dates", year: "Discovery year", place: "Discovery place", discovery: "Discovery circumstances" }, factsTitle: "Important things to remember", facts: [["Balance matters most", "More is not always better. The body needs electrolytes within balanced ranges."], ["The kidneys manage the system", "The kidneys filter, retain, or excrete electrolytes according to the body’s needs."], ["Exercise and dehydration matter", "Sweating, diarrhea, vomiting, or unbalanced fluid intake can change electrolyte levels."]],
    ions: [
      { id: "sodium", name: "Sodium", symbol: "Na⁺", emoji: "💧", color: "from-sky-400 to-blue-600", location: "Mainly outside cells and in blood fluid", role: "Sodium helps maintain water balance, nerve signals, muscle activity, and blood pressure.", importance: "Proper sodium balance supports blood volume, stable blood pressure, and nerve-muscle communication.", low: "Low sodium is called hyponatremia and may cause headache, weakness, nausea, confusion, and fatigue.", high: "High sodium is called hypernatremia and may cause strong thirst, dryness, confusion, and weakness.", etymology: ["Sodium is historically connected to soda.", "Na comes from Natrium.", "Natrium is related to natron, an ancient mineral salt.", "The Hebrew name is related to an ancient mineral term."], discoverer: "Sir Humphry Davy", life: "1778–1829", year: "1807", place: "Royal Institution, London", discovery: "Davy isolated sodium by electrolysis of molten sodium hydroxide.", visual: "Na⁺ is a sodium atom that lost one electron and carries a positive charge." },
      { id: "potassium", name: "Potassium", symbol: "K⁺", emoji: "❤️", color: "from-emerald-400 to-green-600", location: "Mainly inside cells", role: "Potassium is essential for cell electrical activity, heart rhythm, nerves, and muscles.", importance: "Small changes in potassium can affect muscles and heart rhythm.", low: "Low potassium is called hypokalemia and may cause weakness, cramps, and fatigue.", high: "High potassium is called hyperkalemia and may affect heart rhythm.", etymology: ["Potassium comes from potash.", "K comes from Kalium.", "Kalium is related to alkali.", "The Hebrew name is related to potash."], discoverer: "Sir Humphry Davy", life: "1778–1829", year: "1807", place: "Royal Institution, London", discovery: "Davy isolated potassium by electrolysis of molten potassium hydroxide.", visual: "K⁺ is a potassium atom that lost one electron." },
      { id: "calcium", name: "Calcium", symbol: "Ca²⁺", emoji: "🦴", color: "from-violet-400 to-purple-700", location: "In bones, teeth, blood, and cells", role: "Calcium supports bones, teeth, muscle contraction, blood clotting, nerve signaling, and cell communication.", importance: "Calcium is both a structural material and an important biological signal.", low: "Low calcium may cause tingling, spasms, cramps, and weakness.", high: "High calcium may cause thirst, constipation, fatigue, and sometimes confusion.", etymology: ["Calcium comes from Latin calx, lime or limestone.", "Ca is short for Calcium.", "Calcium compounds were known in limestone and lime.", "The Hebrew name is related to lime."], discoverer: "Sir Humphry Davy", life: "1778–1829", year: "1808", place: "Royal Institution, London", discovery: "Davy isolated calcium using electrolysis of calcium compounds.", visual: "Ca²⁺ is a calcium atom that lost two electrons." },
      { id: "magnesium", name: "Magnesium", symbol: "Mg²⁺", emoji: "💪", color: "from-amber-400 to-orange-600", location: "In cells, muscles, and bones", role: "Magnesium participates in hundreds of enzyme reactions, energy production, muscles, and nerves.", importance: "Magnesium helps many enzymes and supports cellular energy.", low: "Low magnesium may cause cramps, tremor, and fatigue.", high: "High magnesium is uncommon but may cause weakness and sleepiness.", etymology: ["Magnesium is related to Magnesia.", "Mg is short for Magnesium.", "Magnesia was linked to similar minerals.", "The name preserves a connection to the region of Magnesia."], discoverer: "Sir Humphry Davy", life: "1778–1829", year: "1808", place: "Royal Institution, London", discovery: "Davy isolated a small amount of magnesium by electrolysis.", visual: "Mg²⁺ is a magnesium atom that lost two electrons." },
      { id: "chloride", name: "Chloride", symbol: "Cl⁻", emoji: "🧪", color: "from-cyan-400 to-teal-600", location: "Mainly outside cells and in blood", role: "Chloride helps fluid balance, acid-base balance, osmotic pressure, and stomach acid.", importance: "Chloride works with sodium to maintain fluid and acidity balance.", low: "Low chloride may occur after vomiting or fluid loss.", high: "High chloride may occur with dehydration or acid-base disorders.", etymology: ["Chloride is the negative ion of chlorine.", "Chlorine comes from Greek chlōros.", "Cl is short for Chlorine.", "Chloride is chlorine that gained an electron."], discoverer: "Carl Wilhelm Scheele", life: "1742–1786", year: "1774", place: "Sweden", discovery: "Scheele produced a greenish-yellow gas; Davy later identified it as an element.", visual: "Cl⁻ is a chlorine atom that gained an electron and carries a negative charge." },
      { id: "phosphate", name: "Phosphate", symbol: "PO₄³⁻", emoji: "⚡", color: "from-rose-400 to-pink-700", location: "In cells, bones, teeth, and blood", role: "Phosphate is important for cellular energy, DNA, RNA, membranes, and bone health.", importance: "Phosphate is central to ATP, the cell’s energy currency.", low: "Low phosphate may cause weakness, muscle pain, and low energy.", high: "High phosphate is often related to kidney function and calcium-phosphorus balance.", etymology: ["Phosphate is an ion of phosphoric acid.", "Phosphorus means light-bearer in Greek.", "The name relates to white phosphorus glowing in the dark.", "Phosphate is a compound form of phosphorus."], discoverer: "Hennig Brand", life: "c. 1630–c. 1710", year: "1669", place: "Hamburg, Germany", discovery: "Brand searched for the philosopher’s stone and isolated a glowing substance from urine.", visual: "PO₄³⁻ is a compound ion with phosphorus and four oxygen atoms." }
    ]
  }
};
